import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';

interface TypeNode {
    kind: string;
    format?: string;
    item?: TypeNode;
    items?: TypeNode[];
    type?: TypeNode;
    fields?: FieldNode[];
    key?: TypeNode;
    value?: TypeNode;
    number?: TypeNode;
    variants?: VariantNode[];
    name?: string;
    prefix?: TypeNode | TypeNode[];
    encoding?: string;
    count?: unknown;
    decimals?: number;
    unit?: string;
    offset?: number;
    strategy?: string;
    size?: TypeNode;
    struct?: TypeNode;
    tuple?: TypeNode;
}

interface VariantNode {
    kind: string;
    name: string;
    struct?: TypeNode;
    tuple?: TypeNode;
}

interface FieldNode {
    name: string;
    type: TypeNode;
    defaultValueStrategy?: string;
}

interface AccountNode {
    name: string;
    isOptional?: boolean;
    defaultValue?: unknown;
}

interface DefinedTypeNode {
    kind: string;
    name: string;
    type: TypeNode;
}

interface InstructionNode {
    name: string;
    arguments: FieldNode[];
    accounts: AccountNode[];
}

interface IdlRoot {
    program: {
        name: string;
        instructions: InstructionNode[];
        definedTypes?: DefinedTypeNode[];
    };
}

/**
 * Discovers all IDL JSON files in tests/idls/ and generates
 * a corresponding type file for each one in tests/generated/.
 */
async function main() {
    const idlsDir = path.resolve(import.meta.dirname, '..', 'tests', 'idls');
    const outputDir = path.resolve(import.meta.dirname, '..', 'tests', 'generated');

    const idlFiles = readdirSync(idlsDir).filter(f => f.endsWith('.json'));

    if (idlFiles.length === 0) {
        console.error(`No IDL JSON files found in ${idlsDir}`);
        process.exit(1);
    }

    mkdirSync(outputDir, { recursive: true });

    for (const file of idlFiles) {
        const idlPath = path.join(idlsDir, file);
        const outputFile = file.replace(/\.json$/, '-types.ts');
        const outputPath = path.join(outputDir, outputFile);

        console.log(`Reading IDL from: ${idlPath}`);
        const idlJson = readFileSync(idlPath, 'utf-8');
        const idl: IdlRoot = JSON.parse(idlJson);

        console.log(`Generating types for program: ${idl.program.name}`);
        const types = generateProgramClientType(idl);

        console.log(`Writing types to: ${outputPath}`);
        writeFileSync(outputPath, types, 'utf-8');
    }

    console.log(`Done — generated types for ${idlFiles.length} program(s)`);
}

await main();

/**
 * Generate TypeScript type for program client.
 */
export function generateProgramClientType(idl: IdlRoot): string {
    const programName = toPascalCase(idl.program.name);
    const definedTypes = idl.program.definedTypes ?? [];

    let output = `/**
 * Auto-generated types for strongly-typed ProgramClient
 * DO NOT EDIT - Generated by scripts/generate-program-client-types.ts
 *
 * Note: When the IDL contains types that cannot be resolved (e.g. unsupported
 * kind, missing definition), argument types fall back to \`unknown\` instead of
 * \`any\`. Consumers should narrow these values before use.
 */

import type { InstructionNode, RootNode } from 'codama';
import type { Address } from '@solana/addresses';
import type { Instruction } from '@solana/instructions';

/**
 * Method builder interface.
 */
export type MethodBuilder<TAccounts> = {
    accounts(accounts: TAccounts): {
        instruction(): Promise<Instruction>;
    };
};

`;

    for (const ix of idl.program.instructions) {
        const typeName = toPascalCase(ix.name);

        // Build args interface
        const args = ix.arguments.filter(arg => arg.defaultValueStrategy !== 'omitted');
        let argsRef = 'void';
        if (args.length > 0) {
            const argsInterfaceName = `${typeName}Args`;
            output += `export type ${argsInterfaceName} = {\n`;
            for (const arg of args) {
                output += `    ${arg.name}: ${codamaTypeToTS(arg.type, definedTypes)};\n`;
            }
            output += '};\n\n';
            argsRef = argsInterfaceName;
        }

        // Build accounts interface
        const accountFields = ix.accounts.filter(acc => !acc.defaultValue);
        const accountsInterfaceName = `${typeName}Accounts`;
        if (accountFields.length > 0) {
            output += `export type ${accountsInterfaceName} = {\n`;
            for (const acc of accountFields) {
                const type = acc.isOptional ? 'Address | null' : 'Address';
                output += `    ${acc.name}: ${type};\n`;
            }
            output += '} & Record<string, Address | null | undefined>;\n\n';
        } else {
            output += `export type ${accountsInterfaceName} = Record<string, Address | null | undefined>;\n\n`;
        }

        // Generate method type
        const methodSignature =
            argsRef === 'void'
                ? `() => MethodBuilder<${accountsInterfaceName}>`
                : `(args: ${argsRef}) => MethodBuilder<${accountsInterfaceName}>`;
        output += `export type ${typeName}Method = ${methodSignature};\n\n`;
    }

    output += `/**
 * Strongly-typed methods for ${programName}.
 */
export type ${programName}Methods = {\n`;

    for (const ix of idl.program.instructions) {
        const typeName = toPascalCase(ix.name);
        output += `    ${ix.name}: ${typeName}Method;\n`;
    }

    output += '};\n\n';

    output += `/**
 * Strongly-typed program client for ${programName}.
 */
export type ${programName}ProgramClient = {
    methods: ${programName}Methods;
    programAddress: Address;
    root: RootNode;
    instructions: Map<string, InstructionNode>;
};
`;

    return output;
}

/**
 * Convert Codama type to TypeScript type string.
 */
function codamaTypeToTS(type: TypeNode | undefined, definedTypes: DefinedTypeNode[]): string {
    if (!type || typeof type !== 'object') return 'unknown';

    switch (type.kind) {
        case 'numberTypeNode':
            return ['u64', 'u128', 'i64', 'i128'].includes(type.format ?? '') ? 'number | bigint' : 'number';
        case 'publicKeyTypeNode':
            return 'Address';
        case 'stringTypeNode':
            return 'string';
        case 'booleanTypeNode':
            return 'boolean';
        case 'optionTypeNode':
            return `${codamaTypeToTS(type.item, definedTypes)} | null | undefined`;
        case 'remainderOptionTypeNode':
        case 'zeroableOptionTypeNode':
            return `${codamaTypeToTS(type.item, definedTypes)} | null`;
        case 'bytesTypeNode':
            return 'Uint8Array';
        case 'fixedSizeTypeNode':
        case 'sizePrefixTypeNode':
        case 'hiddenPrefixTypeNode':
        case 'preOffsetTypeNode':
        case 'postOffsetTypeNode':
            return codamaTypeToTS(type.type, definedTypes);
        case 'amountTypeNode':
            return 'number | bigint';
        case 'structTypeNode': {
            if (!type.fields || type.fields.length === 0) return '{}';
            const fields = type.fields
                .filter(f => f.defaultValueStrategy !== 'omitted')
                .map(f => `${f.name}: ${codamaTypeToTS(f.type, definedTypes)}`);
            if (fields.length === 0) return '{}';
            return `{ ${fields.join('; ')} }`;
        }
        case 'enumTypeNode': {
            if (!type.variants || type.variants.length === 0) return 'unknown';
            const allEmpty = type.variants.every(v => v.kind === 'enumEmptyVariantTypeNode');
            if (allEmpty) {
                return type.variants.map(v => `'${v.name}'`).join(' | ');
            }
            // Enum with struct/tuple variants — discriminated union
            const variantTypes = type.variants.map(v => {
                if (v.kind === 'enumEmptyVariantTypeNode') {
                    return `{ __kind: '${v.name}' }`;
                }
                if (v.kind === 'enumStructVariantTypeNode' && v.struct) {
                    const inner = codamaTypeToTS(v.struct, definedTypes);
                    return `{ __kind: '${v.name}' } & ${inner}`;
                }
                if (v.kind === 'enumTupleVariantTypeNode' && v.tuple) {
                    const inner = codamaTypeToTS(v.tuple, definedTypes);
                    return `{ __kind: '${v.name}'; fields: ${inner} }`;
                }
                return `{ __kind: '${v.name}' }`;
            });
            return variantTypes.join(' | ');
        }
        case 'tupleTypeNode': {
            if (!type.items || type.items.length === 0) return '[]';
            const items = type.items.map(i => codamaTypeToTS(i, definedTypes));
            return `[${items.join(', ')}]`;
        }
        case 'arrayTypeNode': {
            const itemType = codamaTypeToTS(type.item, definedTypes);
            const needsParens = itemType.includes(' | ') || itemType.includes(' & ');
            return needsParens ? `(${itemType})[]` : `${itemType}[]`;
        }
        case 'mapTypeNode': {
            const k = codamaTypeToTS(type.key, definedTypes);
            const v = codamaTypeToTS(type.value, definedTypes);
            return `Map<${k}, ${v}>`;
        }
        case 'definedTypeLinkNode': {
            if (!type.name) return 'unknown';
            const def = definedTypes.find(d => d.name === type.name);
            if (!def) return 'unknown';
            return codamaTypeToTS(def.type, definedTypes);
        }
        default:
            return 'unknown';
    }
}

function toPascalCase(str: string): string {
    return str
        .split(/[-_]/)
        .map(word => word.charAt(0).toUpperCase() + word.slice(1))
        .join('');
}
